config/routes.rb
Rails.application.routes.draw do
  resources :csv_processings
  root 'pages#home'
  resources :accounts

  resources :loyalty_program_data do
    resources :transactions
  end

  resources :transactions

  resources :loyalty_programs do
    post :link
    post :update_conversion_rate
  end
  resources :csv_processing

  # view_accrual
  get 'view_accrual' => 'csv_processing#view_accrual'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # devise_scope :user do
  #   get 'sign_up', to: 'users/registrations#new'
  # end
end

app/models/loyalty_program.rb
class LoyaltyProgram < ApplicationRecord
  after_create :create_loyalty_program_data

  def valid_membership(id)
    if membership_regex
      if id.match(membership_regex)
        puts 'Match found!'
        true
      else
        puts 'Match FAILED'
        false
      end
    else
      puts 'No Valid Regex'
      true
    end
  end

  private

  # create loyalty program data for all users
  def create_loyalty_program_data
    # This doubles the seeding that has been done in user.rb
    User.all.each do |user|
      puts "Creating loyalty program data for user #{user.id}"
      LoyaltyProgramDatum.create(account_id: user.account.id, loyalty_program_id: loyalty_program_id)
    end
  end
end

app/controllers/loyalty_programs_controller.rb
class LoyaltyProgramsController < ApplicationController
  include Authenticable

  before_action :set_loyalty_program, only: %i[show edit update destroy]

  before_action :authenticate_admin!, only: [:update_conversion_rate] # `only` part if applicable

  # GET /loyalty_programs or /loyalty_programs.json
  def index
    @loyalty_programs = LoyaltyProgram.all
  end

  # def GET
  #   respond_to do |format|
  #     if @loyalty_program.save
  #       format.html { redirect_to loyalty_program_url(@loyalty_program), notice: "Loyalty program was successfully created." }
  #       format.json { render :show, status: :created, location: @loyalty_program }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @loyalty_program.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # GET /loyalty_programs/1 or /loyalty_programs/1.json
  def show; end

  # GET /loyalty_programs/new
  def new
    @loyalty_program = LoyaltyProgram.new
  end

  # GET /loyalty_programs/1/edit
  def edit; end

  # POST /loyalty_programs or /loyalty_programs.json
  def create
    @loyalty_program = LoyaltyProgram.new(loyalty_program_params)

    respond_to do |format|
      if @loyalty_program.save
        format.html do
          redirect_to loyalty_program_url(@loyalty_program), notice: 'Loyalty program was successfully created.'
        end
        format.json { render :show, status: :created, location: @loyalty_program }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loyalty_program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loyalty_programs/1 or /loyalty_programs/1.json
  def update
    respond_to do |format|
      if @loyalty_program.update(loyalty_program_params)
        format.html do
          redirect_to loyalty_program_url(@loyalty_program), notice: 'Loyalty program was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @loyalty_program }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loyalty_program.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_conversion_rate
    @loyalty_program = LoyaltyProgram.find(params[:loyalty_program_id])
    if params[:conversion_rate].present?
      @loyalty_program.conversion_rate = params[:conversion_rate]
      @loyalty_program.save
      redirect_to loyalty_program_url(@loyalty_program),
                  notice: 'Loyalty Program Conversion Rate Changed.'
    end
  end

  # DELETE /loyalty_programs/1 or /loyalty_programs/1.json
  def destroy
    @loyalty_program.destroy

    respond_to do |format|
      format.html { redirect_to loyalty_programs_url, notice: 'Loyalty program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def link
    @loyalty_program = LoyaltyProgram.find(params[:loyalty_program_id])
    # byebug

    validity = @loyalty_program.valid_membership(params[:membership_id])

    respond_to do |format|
      if validity
        format.html do
          redirect_to loyalty_program_url(@loyalty_program),
                      notice: 'Loyalty Program Membership was successfully linked.'
        end
        # format.json { head :no_content }
      else
        # format.html { redirect_to loyalty_program_url(@loyalty_program), notice: "Loyalty Program Membership was not found!" }
        # format.json { head :no_content }
        format.html do
          redirect_to loyalty_program_url(@loyalty_program), notice: 'Loyalty Program Membership could not be linked!',
                                                             status: :unprocessable_entity
        end
        # @loyalty_program.new :error
        @loyalty_program.errors[:validity] << ['Loyalty Program Membership could not be linked!']
        format.json { render json: @loyalty_program.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_loyalty_program
    @loyalty_program = LoyaltyProgram.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def loyalty_program_params
    params.require(:loyalty_program).permit(:loyalty_program_id, :program_name, :currency_name, :processing_time,
                                            :description, :enrollment_link, :terms_and_conditions_link, :membership_regex)
  end

  def loyalty_program_admin_params
    params.require(:loyalty_program).permit(:loyalty_program_id, :program_name, :currency_name, :processing_time,
                                            :description, :enrollment_link, :terms_and_conditions_link, :membership_regex, :conversion_rate)
  end
end

app/helpers/loyalty_programs_helper.rb
module LoyaltyProgramsHelper
end

app/views/loyalty_programs/_form.html.erb
<%= form_with(model: loyalty_program) do |form| %>
  <% if loyalty_program.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(loyalty_program.errors.count, "error") %> prohibited this loyalty_program from being saved:</h2>

      <ul>
        <% loyalty_program.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :loyalty_program_id, style: "display: block", class: "text-light" %>
    <%= form.text_field :loyalty_program_id %>
  </div>

  <div>
    <%= form.label :program_name, style: "display: block", class: "text-light" %>
    <%= form.text_field :program_name %>
  </div>

  <div>
    <%= form.label :currency_name, style: "display: block", class: "text-light" %>
    <%= form.text_field :currency_name %>
  </div>

  <div>
    <%= form.label :processing_time, style: "display: block", class: "text-light" %>
    <%= form.text_field :processing_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class: "text-light" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :membership_regex, style: "display: block", class: "text-light" %>
    <%= form.text_field :membership_regex %>
  </div>

  <div>
    <%= form.label :enrollment_link, style: "display: block", class: "text-light" %>
    <%= form.text_field :enrollment_link %>
  </div>

  <div>
    <%= form.label :terms_and_conditions_link, style: "display: block", class: "text-light" %>
    <%= form.text_field :terms_and_conditions_link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/loyalty_programs/_loyalty_program.html.erb
<div id="<%= dom_id loyalty_program %>" class="col-4 p-3">
  <div class="card bg-dark text-light m-1 border border-light">
    <div class="card-body">
      <h5 class="card-title"><%= loyalty_program.program_name %></h5>

      <p>
        <strong>Loyalty program:</strong>
        <%= loyalty_program.loyalty_program_id %>
      </p>

      <p>
        <strong>Program name:</strong>
        <%= loyalty_program.program_name %>
      </p>

      <p>
        <strong>Currency name:</strong>
        <%= loyalty_program.currency_name %>
      </p>

      <p>
        <strong>Conversion_rate:</strong>
        <%= loyalty_program.conversion_rate %>
      </p>

      <p>
        <strong>Processing time:</strong>
        <%= loyalty_program.processing_time %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= loyalty_program.description %>
      </p>

      <p>
        <a href="https://<%=loyalty_program.enrollment_link%>" target="_blank" class="btn btn-sm btn-primary">Enrollment Link</a>
        <a href="https://<%=loyalty_program.terms_and_conditions_link%>" target="_blank" class="btn btn-sm btn-primary">Terms and Conditions</a>
      </p>

      <a href="<%= loyalty_program_path(loyalty_program) %>" class="btn btn-light" name="link_account">Link Account</a>
    </div>
  </div>
</div>

app/views/loyalty_programs/edit.html.erb
<h1>Editing loyalty program</h1>

<%= render "form", loyalty_program: @loyalty_program %>

<br>

<div>
  <%= link_to "Show this loyalty program", @loyalty_program %> |
  <%= link_to "Back to loyalty programs", loyalty_programs_path %>
</div>

app/views/loyalty_programs/index.html.erb
<div class="container mx-auto rounded-xl shadow-sm">
  <h1 class="display-3 text-light pt-2" >Loyalty Programs</h1>
  <div class="row"> 
  <% @loyalty_programs.each do |loyalty_program| %>
      <%= render loyalty_program %>
  <% end %>
  </div>
  <%= link_to "New loyalty program", new_loyalty_program_path, class:"btn btn-primary text-sm font-semibold rounded-full border border-purple-200 hover:text-white hover:bg-purple-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-offset-2" %>
</div>

app/views/loyalty_programs/new.html.erb
<h1 class="text-light">New Loyalty Program</h1>

<%= render "form", loyalty_program: @loyalty_program %>

<br>

<div>
  <%= link_to "Back to Loyalty Programs", loyalty_programs_path %>
</div>

app/views/loyalty_programs/show.html.erb
<div id="<%= dom_id @loyalty_program %>" class="p-0">
  <div class="container bg-dark text-light m-1">
    <div class="card-body">
      <h5 class="card-title"><%= @loyalty_program.program_name %></h5>

      <p>
        <strong>Loyalty program:</strong>
        <%= @loyalty_program.loyalty_program_id %>
      </p>

      <p>
        <strong>Program name:</strong>
        <%= @loyalty_program.program_name %>
      </p>

      <p>
        <strong>Currency name:</strong>
        <%= @loyalty_program.currency_name %>
      </p>

      <p>
        <strong>Conversion Rate:</strong>
        <%= @loyalty_program.conversion_rate %>
      </p>

      <p>
        <strong>Processing time:</strong>
        <%= @loyalty_program.processing_time %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @loyalty_program.description %>
      </p>

      <p>
        <strong>Membership ID Regex:</strong>
        <%= @loyalty_program.membership_regex %>
      </p>

      <p>
        <a href="https://<%=@loyalty_program.enrollment_link%>" target="_blank" class="btn btn-sm btn-info">Enrollment Link</a>
        <a href="https://<%=@loyalty_program.terms_and_conditions_link%>" target="_blank" class="btn btn-sm btn-info">Terms and Conditions</a>
      </p>

    </div>
  </div>
</div>

<div class="ps-4 pb-3">
  <h5 class="text-light">Link Membership ID</h5>

  <%= form_with(url: loyalty_program_link_path(@loyalty_program)) do |form| %>
    <div class="row w-25 ps-3">
    <%= form.text_field :membership_id, class: "input-group-text" %>
    <%= button_to "Submit Membership ID", @loyalty_program, method: :link, class: "btn btn-warning", name: "submit_memID"%>
    </div>
  <% end %>
</div>

<div class="d-flex flex-row justify-content-left pt-2">
  
  <%#= button_to "Edit this loyalty program", edit_loyalty_program_path(@loyalty_program), class: "btn btn-info p-1 m-1" %>
  <%#= button_to "Destroy this loyalty program", @loyalty_program, method: :delete, class: "btn btn-danger p-1 m-1" %>
  
  <%= button_to "Back to loyalty programs", loyalty_programs_path, class: "btn btn-primary p-1 m-1" %>

</div>
<% if current_user.admin %>
<div class="bg-dark text-light m-1"> 
  <h5 class="card-title">Update Conversion rate</h5>

  <%= form_with(url: loyalty_program_update_conversion_rate_path(@loyalty_program)) do |form| %>
    <%= form.text_field :conversion_rate %>
    <%= button_to "Change", @loyalty_program, method: :update_conversion_rate %>
  <% end %>
</div>
<% end %>