config/routes.rb
Rails.application.routes.draw do
  resources :csv_processings
  root 'pages#home'
  resources :accounts

  resources :loyalty_program_data do
    resources :transactions
  end

  resources :transactions

  resources :loyalty_programs do
    post :link
    post :update_conversion_rate
  end
  resources :csv_processing

  # view_accrual
  get 'view_accrual' => 'csv_processing#view_accrual'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # devise_scope :user do
  #   get 'sign_up', to: 'users/registrations#new'
  # end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  # after_action :status_email, only: %i[create edit update new destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.where(account_id: current_user)
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    # StatusMailer.with(user: current_user, transaction_id: @transaction.id).status_email.deliver_now

    respond_to do |format|
      if @transaction.save
        # StatusMailer.with(user: current_user, transaction_id: @transaction.id).status_email.deliver_now
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
        # generate accrual file
        # Thread.new(AccrualProcessor.convert_to_accrual(@transaction))
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def status_email
    puts "EMAIL DELIVERY"
    StatusMailer.with(user: current_user, transaction_id: @transaction.id).status_email.deliver_now
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:loyalty_program, :user, :date, :amount, :status, :loyalty_program_datum_id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %> <% if transaction.errors.any? %>
<div style="color: red">
	<h2>
		<%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being
		saved:
	</h2>

	<ul>
		<% transaction.errors.each do |error| %>
		<li><%= error.full_message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div>
  <%#= form.label :loyalty_program_data, style: "display: block" %> 
  <%#= byebug %> 
  <%#= form.hidden_field :loyalty_program_data, value: LoyaltyProgramData.first %> 
  
  <%# <%= form.label :loyalty_program_data, style: "display: block" %>  %>
  <%#= form.label :loyalty_program_data.account.user, style: "display: block" %> 
</div>

<div>
  <%= form.label :loyalty_program_id, style: "display: block" %> 
  <%= form.select :loyalty_program_id, LoyaltyProgram.all.pluck(:program_name).to_a %>
</div>

<div>
	<%= form.label :transaction_date, style: "display: block" %> 
	<%= form.datetime_select :transaction_date %>
</div>

<div>
  <%= form.label :amount, style: "display: block" %> 
  <%= form.text_field :amount %>
</div>

<div>
	<%= form.label :status, style: "display: block" %>
  <%= form.select :statuses, Transaction.statuses.keys.to_a %>
</div>

<div><%= form.submit %></div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <%# <p>
    <strong>Loyalty program:</strong>
    <%#= transaction.loyalty_program_id.presence %>
  <%# </p> %>

  <%# <p>
    <strong>User:</strong>
    <%= transaction.user_id %>
  <%# </p> %>

  <%# <p>
    <strong>Transaction date:</strong>
    <%= transaction.transaction_date %>
  <%# </p> %>

  <%# <p>
    <strong>Transactions:</strong>
    <%= transaction.transactions_id %>
  <%# </p> %> 

  <%# <p>
    <strong>Amount:</strong>
    <%= transaction.amount %>
  <%# </p> %>

  <%# <p>
    <strong>Status:</strong>
    <%= transaction.status %>
  <%# </p> %>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<h1 class="display-1 pb-2 text-center text-light">Transaction History</h1>

<div id="transactions">
  <div class="container">
    <table class="table table-hover table-striped">
      <thead class="table-head table-dark ">
        <tr>
          <th class="">
            LoyaltyProgramDataID:
          </th>
          <th class="">
            Amount Transferred:
          </th>
          <th class="">
            Transaction Date: 
          </th>
          <th class="">
            Status: 
          </th>
        </tr>
      </thead>
      <tbody class="table-body">
        <% @transactions.each do |transaction| %>
          <tr>
            <td class="text-light">
              <%= transaction.loyalty_program_id %>
            </td>
            <td class="text-light">
              <%= transaction.amount %>
            </td>
            <td class="text-light">
              <%= transaction.created_at %>
            </td>
            <td class="text-light">
              <%= transaction.status %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

  <%#= link_to "New transaction", new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/show.html.erb
<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>