config/routes.rb
Rails.application.routes.draw do
  resources :csv_processings
  root 'pages#home'
  resources :accounts

  resources :loyalty_program_data do
    resources :transactions
  end

  resources :transactions

  resources :loyalty_programs do
    post :link
    post :update_conversion_rate
  end
  resources :csv_processing

  # view_accrual
  get 'view_accrual' => 'csv_processing#view_accrual'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # devise_scope :user do
  #   get 'sign_up', to: 'users/registrations#new'
  # end
end

app/models/account.rb
# Account Model handles details of the user account regarding loyalty program

class Account < ApplicationRecord
  belongs_to :user
  # has_many :loyalty_program_datum
  has_many :loyalty_program_data, class_name: 'LoyaltyProgramDatum'
  after_create :create_loyalty_program_data

  def create_loyalty_program_data
    # creating loyalty program data for account for each loyalty program in callback
    # This doubles the seeding that has been done in user.rb
    # loyalty_program_id = LoyaltyProgram.all.pluck(:id) # Use #pluck as a shortcut to select one or more attributes without loading a bunch of records just to grab the attributes you want

    # # build loyalty program data for each loyalty program

    # loyalty_program_id.each do |i|
    #   user.account.loyalty_program_data.build(loyalty_program_id: i).save
    # end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]
  include AccountsHelper

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show; end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit; end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
        StatusMailer.with(user: @account.user).welcome_email.deliver_now
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_params
    params.require(:account).permit(:user_id)
  end



  def account_points
    @points = LoyaltyProgramData.find(params[:id]).transactions.sum(:points)
    # are we ale to update the account points each time user makes a transcation?
  end

  helper_method :account, :account_points
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def get_account(user_id)
    @account = Account.find(user_id)
    return @account
  end
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= account.user_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this account", account, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this account', edit_account_path(account), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account, class: "contents") do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/accounts/_landing.html.erb
<%= stylesheet_link_tag "landing" %>
<div class="container-fluid text-center text-light">    
  <div class="pt-2"> 
    <h1 class="display-4">Welcome <%= current_user.name %> to Ascenda's Loyalty Account Point Exchange Program</h1>
    <img src="https://careers.recruiteecdn.com/image/upload/production/images/AQcM/m-UAX0dt_4Qa.png" class="py-3 mb-5 my-3 w-75"/>
  </div>
  <div class="d-flex flex-row justify-content-around">
      <div class="m-0 mx-3 px-3">
        <div class="d-flex flex-row justify-content-left mt-2 ms-2">
          <i class="ri-bank-line h4"></i>
        </div>
        <div class="m-0 p-0">
          <p class="h4 fw-bold text-start">Loyalty Programs</p>
          <p class="text-start">Check out our partnering loyalty programs and link your accounts here.</p>
        </div>
          <%= link_to "Loyalty Programs →", loyalty_programs_path, class: "fw-bold btn border mb-2 float-right ms-5 text-light" %>
      </div>
      <div class="m-0 mx-3 px-3">
        <div class="d-flex flex-row justify-content-left mt-2 ms-2">
          <i class="ri-exchange-funds-line h4 float-start"></i>
        </div>
        <div class="m-0 p-0">
          <p class="h4 fw-bold text-start">Exchange Points</p>
          <p class="text-start">Exchange loyalty points from one program to another here.</p>
          <%= link_to "Exchange Points →", loyalty_program_data_path, class: "fw-bold btn border mb-2 float-right ms-5 text-light", name: "exchange" %>
        </div>
      </div>
      <div class="m-0 mx-3 px-3">
        <div class="d-flex flex-row justify-content-left mt-2 mx-2">
        <i class="ri-hand-coin-line h4"></i>
        </div>
        <div class="m-0 p-0">
          <p class="h4 fw-bold text-start">Check Transactions</p>
          <p class="text-start">Check out the history of your previous loyalty program transactions here.</p>
          <%#= link_to "Loyalty Programs →", loyalty_programs_path, class: "fw-bold btn border mb-2 float-right ms-5 text-light" %>
        </div>
        <%= link_to "Transactions →", transactions_path, class: "fw-bold btn border mb-2 float-right ms-5 text-light", name: "trans" %>
      </div>
  </div>
</div>

</body>
</html>

app/views/accounts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing account</h1>

  <%= render "form", account: @account %>

  <%= link_to "Show this account", @account, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to accounts", accounts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/accounts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Accounts</h1>
    <%= link_to 'New account', new_account_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="accounts" class="min-w-full">
    <%= render @accounts %>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New account</h1>

  <%= render "form", account: @account %>

  <%= link_to 'Back to accounts', accounts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/accounts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @account %>

    <%= link_to 'Edit this account', edit_account_path(@account), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this account', account_path(@account), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to accounts', accounts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>